node_js: 'stable'
before_script:
  - npm install -g codecov
install:
  - yarn
cache:
  yarn: true
  directories:
  - node_modules

matrix:
  include:
  - name: 'JavaScript Unit Tests'
    script: 
    - node -v
    - yarn run test
    - codecov

  - name: 'JavaScript Build'
    script: yarn run build