codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...70"

  status:
    project: yes
    patch: yes
    changes: no
  
  ignore:
    - "**/index.js"
    - "src/setupTest.js"
    - "src/serviceWorker.js"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
  javascript:
    enable_partials: yes

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no